/*
 * Copyright (C) 2024 Shubham Panchal
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.shubham0204.smollmandroid.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Material 3 Color Scheme
 * check the role of each color here: https://m3.material.io/styles/color/roles
 */

val primaryLight = Color(0xFF006492)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF00A2E8)
val onPrimaryContainerLight = Color(0xFF00344F)
val secondaryLight = Color(0xFF3D627D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB8DFFE)
val onSecondaryContainerLight = Color(0xFF3D637E)
val tertiaryLight = Color(0xFF8243A0)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC27EE0)
val onTertiaryContainerLight = Color(0xFF500B6E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF6FAFF)
val onBackgroundLight = Color(0xFF171C20)
val surfaceLight = Color(0xFFF6FAFF)
val onSurfaceLight = Color(0xFF171C20)
val surfaceVariantLight = Color(0xFFDAE4EE)
val onSurfaceVariantLight = Color(0xFF3E4850)
val outlineLight = Color(0xFF6E7881)
val outlineVariantLight = Color(0xFFBEC8D2)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3136)
val inverseOnSurfaceLight = Color(0xFFEDF1F7)
val inversePrimaryLight = Color(0xFF8BCEFF)
val surfaceDimLight = Color(0xFFD6DAE0)
val surfaceBrightLight = Color(0xFFF6FAFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4FA)
val surfaceContainerLight = Color(0xFFEAEEF4)
val surfaceContainerHighLight = Color(0xFFE4E8EF)
val surfaceContainerHighestLight = Color(0xFFDEE3E9)

val primaryLightMediumContrast = Color(0xFF003A56)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF0074A7)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF0E3A53)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF4C718D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF561474)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF9252B0)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF6FAFF)
val onBackgroundLightMediumContrast = Color(0xFF171C20)
val surfaceLightMediumContrast = Color(0xFFF6FAFF)
val onSurfaceLightMediumContrast = Color(0xFF0D1216)
val surfaceVariantLightMediumContrast = Color(0xFFDAE4EE)
val onSurfaceVariantLightMediumContrast = Color(0xFF2E373F)
val outlineLightMediumContrast = Color(0xFF4A545C)
val outlineVariantLightMediumContrast = Color(0xFF646E77)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2C3136)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEDF1F7)
val inversePrimaryLightMediumContrast = Color(0xFF8BCEFF)
val surfaceDimLightMediumContrast = Color(0xFFC2C7CD)
val surfaceBrightLightMediumContrast = Color(0xFFF6FAFF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF0F4FA)
val surfaceContainerLightMediumContrast = Color(0xFFE4E8EF)
val surfaceContainerHighLightMediumContrast = Color(0xFFD9DDE3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCED2D8)

val primaryLightHighContrast = Color(0xFF002F48)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004E72)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF002F48)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF264D67)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF4A0269)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF6B2C89)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF6FAFF)
val onBackgroundLightHighContrast = Color(0xFF171C20)
val surfaceLightHighContrast = Color(0xFFF6FAFF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDAE4EE)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF242D35)
val outlineVariantLightHighContrast = Color(0xFF414A53)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2C3136)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF8BCEFF)
val surfaceDimLightHighContrast = Color(0xFFB5B9BF)
val surfaceBrightLightHighContrast = Color(0xFFF6FAFF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEDF1F7)
val surfaceContainerLightHighContrast = Color(0xFFDEE3E9)
val surfaceContainerHighLightHighContrast = Color(0xFFD0D5DB)
val surfaceContainerHighestLightHighContrast = Color(0xFFC2C7CD)

val primaryDark = Color(0xFF8BCEFF)
val onPrimaryDark = Color(0xFF00344E)
val primaryContainerDark = Color(0xFF00A2E8)
val onPrimaryContainerDark = Color(0xFF00344F)
val secondaryDark = Color(0xFFA5CBEA)
val onSecondaryDark = Color(0xFF04344D)
val secondaryContainerDark = Color(0xFF264D67)
val onSecondaryContainerDark = Color(0xFF97BDDB)
val tertiaryDark = Color(0xFFEAB2FF)
val onTertiaryDark = Color(0xFF4F0A6E)
val tertiaryContainerDark = Color(0xFFC27EE0)
val onTertiaryContainerDark = Color(0xFF500B6E)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1418)
val onBackgroundDark = Color(0xFFDEE3E9)
val surfaceDark = Color(0xFF0F1418)
val onSurfaceDark = Color(0xFFDEE3E9)
val surfaceVariantDark = Color(0xFF3E4850)
val onSurfaceVariantDark = Color(0xFFBEC8D2)
val outlineDark = Color(0xFF88929B)
val outlineVariantDark = Color(0xFF3E4850)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E9)
val inverseOnSurfaceDark = Color(0xFF2C3136)
val inversePrimaryDark = Color(0xFF006492)
val surfaceDimDark = Color(0xFF0F1418)
val surfaceBrightDark = Color(0xFF353A3E)
val surfaceContainerLowestDark = Color(0xFF0A0F13)
val surfaceContainerLowDark = Color(0xFF171C20)
val surfaceContainerDark = Color(0xFF1B2025)
val surfaceContainerHighDark = Color(0xFF262B2F)
val surfaceContainerHighestDark = Color(0xFF30353A)

val primaryDarkMediumContrast = Color(0xFFBCE1FF)
val onPrimaryDarkMediumContrast = Color(0xFF00283E)
val primaryContainerDarkMediumContrast = Color(0xFF00A2E8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF00070F)
val secondaryDarkMediumContrast = Color(0xFFBCE1FF)
val onSecondaryDarkMediumContrast = Color(0xFF00283E)
val secondaryContainerDarkMediumContrast = Color(0xFF7095B2)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFF4D0FF)
val onTertiaryDarkMediumContrast = Color(0xFF41005D)
val tertiaryContainerDarkMediumContrast = Color(0xFFC27EE0)
val onTertiaryContainerDarkMediumContrast = Color(0xFF11001C)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1418)
val onBackgroundDarkMediumContrast = Color(0xFFDEE3E9)
val surfaceDarkMediumContrast = Color(0xFF0F1418)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3E4850)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD3DDE8)
val outlineDarkMediumContrast = Color(0xFFA9B3BD)
val outlineVariantDarkMediumContrast = Color(0xFF88919B)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF262B2F)
val inversePrimaryDarkMediumContrast = Color(0xFF004D71)
val surfaceDimDarkMediumContrast = Color(0xFF0F1418)
val surfaceBrightDarkMediumContrast = Color(0xFF40454A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF04080C)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191E23)
val surfaceContainerDarkMediumContrast = Color(0xFF23282D)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3338)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393E43)

val primaryDarkHighContrast = Color(0xFFE4F2FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF81CAFF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000D17)
val secondaryDarkHighContrast = Color(0xFFE4F2FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA1C7E6)
val onSecondaryContainerDarkHighContrast = Color(0xFF000D17)
val tertiaryDarkHighContrast = Color(0xFFFDEAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFE8ADFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF180026)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0F1418)
val onBackgroundDarkHighContrast = Color(0xFFDEE3E9)
val surfaceDarkHighContrast = Color(0xFF0F1418)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3E4850)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE7F1FC)
val outlineVariantDarkHighContrast = Color(0xFFBAC4CE)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF004D71)
val surfaceDimDarkHighContrast = Color(0xFF0F1418)
val surfaceBrightDarkHighContrast = Color(0xFF4C5156)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B2025)
val surfaceContainerDarkHighContrast = Color(0xFF2C3136)
val surfaceContainerHighDarkHighContrast = Color(0xFF373C41)
val surfaceContainerHighestDarkHighContrast = Color(0xFF42474C)
